/** Hard cap on reviewer-supplied extra guide instructions (#1265): the
 *  freeform text appended to the organizer methodology at launch. A hygiene
 *  bound on prompt size, not a security boundary (the instructions run on the
 *  user's own machine against their own agent). Enforced server-side in
 *  composeGuideMethodology and mirrored by the launch textarea's maxLength. */
export const GUIDE_EXTRA_INSTRUCTIONS_MAX_CHARS = 2000;

/** Hard cap on a refinement ask: the one instruction a reader gives about one
 *  guide ("break chapter 3 into its own chapters"). Long enough for a
 *  paragraph of direction, short enough that the diff stays the bulk of the
 *  prompt. Enforced server-side in buildGuideRefineBlock and mirrored by the
 *  refine textarea's maxLength. */
export const GUIDE_REFINE_ASK_MAX_CHARS = 2000;

/** Human labels for the engines that can generate a guide, keyed by the id
 *  stored in a snapshot's `generator.engine`. The one source of truth for the
 *  in-app engine pickers and the portable viewer's "generated by" line. */
export const GUIDE_ENGINE_LABEL = {
  claude: 'Claude',
  codex: 'Codex',
  cursor: 'Cursor',
  opencode: 'OpenCode',
  pi: 'Pi',
  copilot: 'Copilot',
} as const;

export interface GuideDiffRef {
  /** Repo-relative path; must match a DiffFile.path in the current review patch. */
  file: string;
  /** 1-2 sentence semantic description of what changed in THIS file, written
   *  from the diff hunks alone (no investigation). Required by the JSON schema
   *  for schema-enforced engines; optional here so a marker engine that omits
   *  it still yields a valid guide — the UI simply renders nothing. */
  summary?: string;
}

/** A named part of one chapter: its own heading, prose, and diagram.
 *
 *  Deliberately optional and deliberately rare. A chapter with one idea stays
 *  one chapter; the prompt names the three cases that earn a split. Present
 *  only on guides generated after the fork added them, so every renderer must
 *  treat an absent list as "this chapter has no parts", never as an error. */
export interface GuideSubsection {
  /** Concept-level heading for this part of the chapter. */
  title: string;
  /** Markdown prose for this part, diagram included. */
  body: string;
}

export interface GuideSection {
  /** Concept-level title, e.g. "Payment localization module" — never a filename paraphrase. */
  title: string;
  /** Markdown prose: what changed, why it exists, and its key implications.
   *  Semantic order (core first, consequences next, glue grouped last) is
   *  carried by the array position, not by any label field. */
  overview: string;
  /** Optional named parts of this chapter, rendered under the overview. The
   *  overview stays the chapter's summary when they are present; a part
   *  carries the detail. */
  subsections?: GuideSubsection[];
  /** File references into the provided changeset. Usually 1..n, but a
   *  deliberate prose-only context section (no diffs, real overview text) is
   *  a valid model output and is preserved as-is rather than dropped. */
  diffs: GuideDiffRef[];
}

/** One hunk that looks like it does not belong in the changeset, on the
 *  evidence of the code rather than the topic: code nothing calls, a leftover
 *  from an abandoned approach, or a second mechanism for a job the first still
 *  does.
 *
 *  An ANNOTATION on a file, never a placement. The file keeps its chapter, so
 *  the coverage rule (every file in exactly one place) is untouched by this
 *  list and `validateGuideOutput` does not consider it. */
export interface GuideLooseEnd {
  /** Repo-relative path; matches a DiffFile.path in the current review patch. */
  file: string;
  /** Why this looks out of place, in one or two plain sentences. */
  note: string;
}

export interface CodeGuideOutput {
  /** From the PR title when a PR is given, otherwise derived from the changes. */
  title: string;
  /** 1-2 sentence framing shown under the title: why this changeset exists. */
  intent: string;
  /** Ordered sections: core first, consequence next, support last. */
  sections: GuideSection[];
  /** Changed files the model didn't place — rendered in a trailing "Everything else" section. */
  unplacedFiles?: string[];
  /** Hunks that look out of place on the evidence of the code — rendered in a
   *  trailing "Loose ends" card. Absent and empty both render nothing. */
  looseEnds?: GuideLooseEnd[];
}

/** One row of GET /api/guides — a persisted guide for the current repo
 *  (#1112). Loaded through the guide endpoints as the `saved:{id}` pseudo
 *  job id. Browser-safe (types only); the store lives in guide-store.ts. */
export interface SavedGuideListEntry {
  id: string;
  /** Review-target label — "PR #1082" or the branch name. */
  label: string;
  title: string;
  /** Epoch ms when the guide was first persisted. */
  savedAt: number;
  progress: { reviewed: number; total: number };
  /** True when the stored head sha differs from the current head. */
  moved: boolean;
}

/** UI-side guide shape: server output extended with persisted per-section reviewed state.
 *  `saved` is set when the guide is persisted on disk (autosaved live job, or a
 *  `saved:{id}` load); `moved` is set only on `saved:` loads whose stored head
 *  sha differs from the head currently under review. */
export type CodeGuideData = CodeGuideOutput & { reviewed: boolean[]; saved?: boolean; moved?: boolean };
